controller_list:
    - name: "/left/ar3/controllers/position"
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6
    - name: "/left/ar3/controllers/grip_position"
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - actuator_joint_1
          - actuator_joint_2
          - actuator_joint_3

