/left/ar3/controllers:
# Publish all joint states
    state:
        type: "joint_state_controller/JointStateController"
        publish_rate: 50
        
    # Joint Trajectory Controller
    position:
        type: "position_controllers/JointTrajectoryController"
        joints: 
            - joint_1  
            - joint_2
            - joint_3  
            - joint_4  
            - joint_5  
            - joint_6

        #gains:
        #    joint_1: {p: 0, d: 0, i: 0}
        #    joint_2: {p: 0, d: 0, i: 0}
        #    joint_3: {p: 0, d: 0, i: 0}
        #    joint_4: {p: 0, d: 0, i: 0}
        #    joint_5: {p: 0, d: 0, i: 0}
        #    joint_6: {p: 0, d: 0, i: 0}

        constraints:
            goal_time: 0.5
            joint_1:
                trajectory: 0.5
                goal: 0.02
            joint_2:
                trajectory: 0.5
                goal: 0.02
            joint_3:
                trajectory: 0.5
                goal: 0.02
            joint_4:
                trajectory: 0.5
                goal: 0.02
            joint_5:
                trajectory: 0.5
                goal: 0.02
            joint_6:
                trajectory: 0.5
                goal: 0.02

    # Same gains as above
    #gazebo_ros_control/pid_gains:
    #    joint_1: {p: 0, d: 0, i: 0}
    #    joint_2: {p: 0, d: 0, i: 0}
    #    joint_3: {p: 0, d: 0, i: 0}
    #    joint_4: {p: 0, d: 0, i: 0}
    #    joint_5: {p: 0, d: 0, i: 0}
    #    joint_6: {p: 0, d: 0, i: 0}


