stepper_config:
  num_joints: 6
  joint_names:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - gripper_joint
  # neg flips direction
  deg_per_step:
    - -0.0225   # 1.8 / 20 / 4
    - 0.036     # 1.8 / 50
    - -0.036    # 1.8 / 50
    - 0.04378   # 1.8 / 14 / 2.938
    - 0.18      # 1.8 / 10 
    - 1
    - 1